const FORM_STATUS = {
  VALID: 'VALID',
  INVALID: 'INVALID',
  LOADING: 'LOADING',
};

const FORM_SUBMIT_RESPONSE_TYPES = {
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
};

export { FORM_STATUS, FORM_SUBMIT_RESPONSE_TYPES };
